print ("Hello Wolrd")
print ("I am learning Python")
print (" I am willing to put the hard work")
print ("Learning Python is so cool so i can land an amazing job")
print(1+1)
print(1-1)
print(1*1)
print(1/1)
print(5000*1)
